# This is a basic workflow to help you get started with Actions

name: firstActionTestypants

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push
  # branches:
  #   - main
  # pull_request:
  #   branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: NPM Install
        run: npm install
      # - name: Run Jest #:( WHy no tests klee
      #   run: npm test
      - name: Run Lint
        run: npm run lint
      - name: Run Prettier
        run: npm run prettier:check
      - name: Gatsby Build
        run: npm run build
      - name: zip build resulit
        run: tar -czvf build.tar.gz public
      - name: archive zip
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build.tar.gz
  deploy:
    needs:
      - build
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: extract build
        run: tar -xzvf build.tar.gz
      - name: publish
        run: echo "yep lets do that"
